# Get info
GET http://localhost:3001/info

###
# Get all entries
GET http://localhost:3001/api/persons

###
# Get single entry
GET http://localhost:3001/api/persons/5

###
# Remove single entry
DELETE http://localhost:3001/api/persons/1