# Get info
GET http://localhost:3001/info

###
# Get all entries
GET http://localhost:3001/api/persons

###
# Get entry
GET http://localhost:3001/api/persons/5

###
# Remove entry
DELETE http://localhost:3001/api/persons/1

###
# Add entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test Person",
    "number": "123"
}