# Get info
GET http://localhost:3001/info

###
# Get all entries
GET http://localhost:3001/api/persons

###
# Get entry
GET http://localhost:3001/api/persons/602eb0b564ef908e0a038ec7

###
# Remove entry
DELETE http://localhost:3001/api/persons/602eb23c5dcdfa8ed13d3967

###
# Add entry
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test Person2",
    "number": "1234-abc-321"
}

###
# Update entry
PUT http://localhost:3001/api/persons/602eb0b564ef908e0a038ec7
Content-Type: application/json

{
    "name": "Test Person",
    "number": "12345678"
}