# Get info
GET https://secret-savannah-49654.herokuapp.com/info

###
# Get all entries
GET https://secret-savannah-49654.herokuapp.com/api/persons

###
# Get entry
GET https://secret-savannah-49654.herokuapp.com/api/persons/5

###
# Remove entry
DELETE https://secret-savannah-49654.herokuapp.com/api/persons/602fc831e5552600158d2a25

###
# Add entry
POST https://secret-savannah-49654.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Test Person 3",
    "number": "123asdfasdf"
}